### ISSUE TITLE
Exception: parameter not supplied while parameter is nevertheless supplied when using USP in a report query

### ISSUE THREAD

**Issue by rvdpluijm** [Seddryck/NBi#156]
Using the tip provide by FuegoArtificial in #155, I inserted parameters for my test on a report query, which executes a stored procedure:

``` xml
    <test name="Initiële test Reportingserver Database">
        <system-under-test>
            <execution>
                <report 
                connectionString="Data Source=brytta;Database=HR_DWH_FIN_RAPO;
User Id=########;Password=########;"
                source="Data Source=brytta;Database=ReportServer;
User Id=########;Password=########;"
                path="/Ontwikkel/Infoview/Financieel/" 
                name="kpl_proj_hierarchie" 
                dataset="kpl_proj"
                >
                    <parameter name="DI" sql-type="varchar(max)">'525'</parameter>
                    <parameter name="status_kpl" sql-type="varchar(30)">'niet actief'</parameter>
                    <parameter name="privaat_publiek" sql-type="varchar(30)">'kppubliek'</parameter>
                </report>
            </execution>
        </system-under-test>
        <assert>
            <row-count>
                <more-than or-equal="true">10</more-than>
            </row-count>
        </assert>
    </test>
```

As one can see, I add the parameter called "DI" here. I still receive an error for not providing the first parameter:

```
NBi.NUnit.Runtime.TestSuite.Initiële test Reportingserver Database:
System.Data.SqlClient.SqlException : Procedure or function 'usp_kpl_proj' expects parameter '@DI',
 which was not supplied.
```

_Further Information_
In the report, the parameter is passed to the stored procedure via a dropdown box and a custom query defining a data set which fills the dropdown box.

Data set query for dropdown box:

``` xml
 <DataSet Name="DI_HR">
      <Query>
        <DataSourceName>HR_DWH</DataSourceName>
        <CommandText>select distinct left(kostenplaats, 3) as DI_CODE, 
case when left(kpl.kostenplaats, 3) = '702' then 'FIT lokaties' when left(kpl.kostenplaats, 3) = '700' then 'FIT overkoepelend' else kp_code_groepniveau2_omschrijving end as DI_omschrijving
from kpl where administratie = 'HR' and type = 'kostenplaats' and einddatum_record is null and kp_code_groepniveau1 is not null and statusactief = 'actief'
group by left(kostenplaats, 3), kp_code_groepniveau2_omschrijving</CommandText>
      </Query>
      <Fields>
        <Field Name="DI_CODE">
          <DataField>DI_CODE</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="DI_omschrijving">
          <DataField>DI_omschrijving</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
      </Fields>
    </DataSet>
```

Definition of the report parameter:

``` xml
    <ReportParameter Name="DI">
      <DataType>String</DataType>
      <DefaultValue>
        <DataSetReference>
          <DataSetName>DI_HR</DataSetName>
          <ValueField>DI_CODE</ValueField>
        </DataSetReference>
      </DefaultValue>
      <Prompt>Dienst/Instituut</Prompt>
      <ValidValues>
        <DataSetReference>
          <DataSetName>DI_HR</DataSetName>
          <ValueField>DI_CODE</ValueField>
          <LabelField>DI_omschrijving</LabelField>
        </DataSetReference>
      </ValidValues>
      <MultiValue>true</MultiValue>
    </ReportParameter>

  <ReportParameter Name="status_kpl">
      <DataType>String</DataType>
      <DefaultValue>
        <Values>
          <Value>actief</Value>
        </Values>
      </DefaultValue>
      <Prompt>status kostenplaats</Prompt>
      <ValidValues>
        <ParameterValues>
          <ParameterValue>
            <Value>actief</Value>
            <Label>actief</Label>
          </ParameterValue>
          <ParameterValue>
            <Value>niet actief</Value>
            <Label>niet actief</Label>
          </ParameterValue>
        </ParameterValues>
      </ValidValues>
      <MultiValue>true</MultiValue>
    </ReportParameter>

    <ReportParameter Name="privaat_publiek">
      <DataType>String</DataType>
      <DefaultValue>
        <Values>
          <Value>KPPRIVAAT</Value>
          <Value>KPPUBLIEK</Value>
        </Values>
      </DefaultValue>
      <Prompt>privaat/publiek</Prompt>
      <ValidValues>
        <ParameterValues>
          <ParameterValue>
            <Value>KPPRIVAAT</Value>
            <Label>privaat</Label>
          </ParameterValue>
          <ParameterValue>
            <Value>KPPUBLIEK</Value>
            <Label>publiek</Label>
          </ParameterValue>
        </ParameterValues>
      </ValidValues>
      <MultiValue>true</MultiValue>
    </ReportParameter>
```

Thank you so much for your help (and your fantastic product at that)!

**Comment by Seddryck** [comment]
I've never tried to send parameters to a stored procedure (I prefer TVF than SP), so I can't confirm it effectively works.

The fact that the SQL parameter is communicated through a dropdown or any other way shouldn't influence the usage of the parameters. 

Could you post the RDL definition of your dataset `kpl_proj` so I can create a sample to reproduce your problem?

**Comment by rvdpluijm** [comment]
Hi @Seddryck, this is the file we are using. I had to convert it to a text file due to Github's restrictions.

[kpl_proj_hierarchie.txt](https://github.com/Seddryck/NBi/files/80941/kpl_proj_hierarchie.txt)

By the way, do you need the definition of the USP? I reckoned not, but perhaps you would need the syntax of the output?

**Comment by Seddryck** [comment]
It will be enought, I'll try to check this as soon as I've a minute. 

But at a first look, it sounds that NBi is not able to interpret correctly that you're supplying a USP. It'd be an easy development to detect that you're supplying a USP and not a query but it must be implemented. If I confirm this, I'll add this as a feature-request and implement it in 1.13

Possible work-around (haven't tried): change your USP by a command `EXEC usp_kpl_proj @DI, @status_kpl, @privaat_publiek` . Not something I'd recommend but will probably fix your testing issue.

**Comment by rvdpluijm** [comment]
Perfect, thanks! I'll try your workaround (although I'm currently in doubt whether I shouldn't just check the recordset from the USP itself instead from the data set and just provide the parameters as usual with a query).

EDIT: I sadly won't be able to test it before Monday, however (not in office tomorrow and leaving early today). Will keep you posted.

**Comment by Seddryck** [comment]
NBi doesn't support a call to an USP just be declaring its name ... The workaoround is to use the `EXEC ...`statement but I'll support this in a near future.

**Comment by daj102** [comment]
Just to add - we've just run into this issue as well, so we would love to see it fixed.  As you say, @Seddryck it just seems to be that NBI is not determining that the dataset is coming from a stored procedure and therefore adding the parameters names to the command text.  This should be a fairly simple fix, though, as the query NBI is using to find the dataset in the first place actually returns a column called CommandType, which for me is showing as 'StoredProcedure' (I did some SQL Profiling of NBI test runs).  If we can just use that to determine how to execute the command, it should be easily fixed. :-) Not that I would know where to start, of course .... :-(

**Comment by Seddryck** [comment]
I'm trying to implement this but I have not the expected environment (SSRS) to test it on my current computer.

This feature is available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.44/artifacts You feedback will be extermely useful to debug this if any issue ... and if by miracle it works ... tell me!

**Comment by daj102** [comment]
I just ran it and I get a different error ... I profiled the database while I ran the test, and it hit the ReportServer database with the exact same query, and got a single record back withe the details of the dataset (StoredProcedure, name of sproc, etc).  However, the error that comes back from nUnit is this (sorry - this doesn't seem to come out in the log file, even though I set logging to Verbose):

NBi.NUnit.Runtime.TestSuite.Quote Report:
System.ArgumentException : No report found on path '/CoverysEDW/Reports/' with name 'Quote Report'
at NBi.Core.Report.DatabaseParser.ExtractQuery(IQueryRequest request) in c:\projects\nbi\NBi.Core\Report\DatabaseParser.cs:line 39
at NBi.Xml.Items.ReportXml.GetQuery() in c:\projects\nbi\NBi.Xml\Items\ReportXml.cs:line 53
at NBi.NUnit.Builder.AbstractExecutionBuilder.InstantiateSystemUnderTest(ExecutionXml executionXml) in c:\projects\nbi\NBi.NUnit\Builder\AbstractExecutionBuilder.cs:line 34
at NBi.NUnit.Builder.AbstractExecutionBuilder.BaseBuild() in c:\projects\nbi\NBi.NUnit\Builder\AbstractExecutionBuilder.cs:line 26
at NBi.NUnit.Builder.AbstractTestCaseBuilder.Build() in c:\projects\nbi\NBi.NUnit\Builder\AbstractTestCaseBuilder.cs:line 52
at NBi.NUnit.TestCaseFactory.Instantiate(AbstractSystemUnderTestXml sutXml, AbstractConstraintXml ctrXml) in c:\projects\nbi\NBi.NUnit\TestCaseFactory.cs:line 144
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in c:\projects\nbi\NBi.NUnit.Runtime\TestSuite.cs:line 80

But it does exist, and the profile results tells me that it returned a row with the details from the database.  It's not a random error either - I can't see the query hit the database for the stored procedure.

**Comment by Seddryck** [comment]
Thx for the feedback, it's appreciated. I committed two changesets to fix your bug and another (should return Text and not T-SQL). I hope, it's better. Anyway it will be the last for today, it's time to go to bed when you're permuting != and ==.

New build available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.46/artifacts

**Comment by daj102** [comment]
Sorry - still no go.  I checked that it was reloading the tests and properly hitting the db by changing the name of the report to something that _didn't_ exist ... and I got this error:

NBi.NUnit.Runtime.TestSuite.Quote Report:
System.NullReferenceException : Object reference not set to an instance of an object.

Which is kinda fair because nothing comes back (i checked in SSMS and Profiler), but a nicer error message would be good :-)  Then, when I changed it back to a report that does exist, I get this error:

NBi.NUnit.Runtime.TestSuite.Quote Report:
System.ArgumentException : No report found on path '/CoverysEDW/Reports/' with name 'Quote Report'

which is not true, and I know there is something that comes back from the DB.

I'm trying to get the source to compile on my machine but I'm having issues finding all the references for SQL Server, but if I get that running I will let you know and we maybe I could play locally ...

**Comment by Seddryck** [comment]
Huuum, are you sure you downloaded 1.13.0-ci46 and not ci45? With a static review of the code, I don't see my mistake. Will check as soon as I've some free time.

**Comment by daj102** [comment]
Turns out that 7-zip did not overwrite .44 properly (doh).  BTW - _love_ it when code has all the build numbers and CI information in, so I can just right-click, view Details and tell which version I have :-)

After checking I had .46, it works :-)  So I would consider this bug closed.

I've got some feedback though ...
- The parameters you need to supply are the exact sproc parameter names, not the Report parameter names.  I wonder if that would be useful to testers to use the _report_ parameter names?  Otherwise, why even have the report node, when you have to know the exact interface to the stored procedure anyway?  You could just use a normal sproc unit test ..,
- The documentation doesn't specify, but you also need to specify the connectionString value in the report node.  If you don't you get an error saying it is not initialized.  I would expect that if we were testing the report, we would want it to use the connection string of the SSRS data source connected to the report.
- The report tag expects to go to a SQL query or a sproc; does it support MDX queries?  We have many data sets that support parameters in our reports, that come from cubes.

Hopefully this feedback is _useful_ ... it is not intended to be criticism, merely feedback. :-)  I've used NBI on several projects and I love that it allows me to bring BI development kicking and screaming into the 21st century - great work!

**Comment by daj102** [comment]
BTW - noticed that NBi.Core.SqlServer2012.dll and the pdb file is missing from build .46 ... is that intentional?

**Comment by Seddryck** [comment]
Good news that it works, I'll now add a few tests for rdl files and create a beta for 1.13 before the final version. Yes, I know that CI builds don't include a dll for SQL Server 2012, it's an issue linked to AppVeyor.

Thx also for your feedback, really interesting to have different point of views, especially about reports. I know that NBi is light for testing reports, it's related to my vision of BI where reporting is avoided as much as possible (it represents less than 1% of the team work). When we build reports, my standard is to hide the complexity of the dataset as much as possible with a view or a TVF ... testable by itself. In my vision, you should only test that your query embedded in the report is syntactically correct  (and test the view/TVF). It's probably why some "obvious" features are missing.
- I get your point about parameters and created #179
- Probably because I often test on the rdl itself (and not on the report hosted in database). The relative path of the data source could be not so obvious ... but will also consider this in #180
- Yes it supports MDX

**Comment by daj102** [comment]
I think that report unit testing would have to test the report rendering itself.  Personally, I would love to see the ability to test the underlying stored procedures of the report, where we can directly inject parameters and test result sets (which is possible right now, and is essentially what the <report> node is doing.  However, once you do that, when you test a report you want to test what is _above_ that - in other words, do the parameters from the report correctly connect to the stored procedure, do the results come back and does it render correctly?  If you think of an SSRS report as two layers (rendering on top of data retrieval), then you can already test the data retrieval with direct sproc access ... so I would have hoped that the report testing would test the remaining part of the actual rendering.

For example, I could have two tests - one that checks the sproc returns 5 rows.  But then another test that tests the report with the same parameter values at the report level ... and then it checks the returned HTML (or something - maybe we could render a CSV?) that it shows 5 rows.  Or maybe because it is grouped with totals, we would expect _6_ rows.  The current <report> test doesn't seem to be able to do that bit.

Again, though, I really appreciate all the work you do on this - thank you!

**Comment by Seddryck** [comment]
About rendering of the report, it's a work in progress (since long). The idea is to use the xml output of the report and define XPATH queries on top of it to compare to a result-set (and take the benefits of all assertions already defined for a result-set such as row-counts, equalTo, ...). It's basically the content of #40 

I'm closing this thread (because initial request is solved) but feel free to submit new ideas or to comment in the corresponding issues for other ideas.
