### ISSUE TITLE
Missing DLL when using setup/sql-run

### ISSUE THREAD

**Issue by Tannenwedel** [Seddryck/NBi#396]
Hi,

I'm trying to a SQL script before my test like this:

 <setup>
      <sql-run
          name="dq-setup.sql"
          path="../dq/"
          connectionString="..."
        />
  </setup>

But this results in this error message:

NBi.NUnit.Runtime.TestSuite.DQ:
Exception during the setup of the test: Could not load file or assembly 'Microsoft.SqlServer.SqlEnum, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at NBi.Core.SqlServer.Smo.BatchRunCommand.Execute()
   at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup) in C:\projects\nbi\NBi.NUnit.Runtime\TestSuite.cs:line 149

There is no Microsoft.SqlServer.SqlEnum.dll in the Framework directory.

**Comment by Seddryck** [comment]
Do you use a beta version compiled on AppVeyor?
Do you use SQL Server 2017?

AppVeyor’s build agents don’t have the necessary dlls to build the extension for SQL Server 2017 ... but this extension is stable and hasn’t changed since 1.18

If both answers to the questions are true then you should download the v1.18 from [nbi.io](http://www.nbi.io) and copy the Microsoft dll dedicated to SQL Server 2017 (don’t change the NBi ones)

**Comment by Tannenwedel** [comment]
I downloaded NBi 1.18.0.1 and copied the SqlServer2017 files into the Framework directory. The error message remains the same.
Is Microsoft.SqlServer.SqlEnum.dll supposed to be picked up from my system files (e.g. local SQL Server installation files)? Are the DLLS in framework 32 or 64 bit?

**Comment by Seddryck** [comment]
It's a bit complex and not well documented on Microsoft side but usually when you've SQL Server on your machine, these dll are already instalIed and referenced on the GAC. Anyway, NBi shouldn't rely on that.

I pushed a new version of the beta at https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.43.build.434/artifacts and it contains the Microsoft.SqlServer.SqlEnum.dll ... hope that some other dlls from SQL Server are not missing.

**Comment by Tannenwedel** [comment]
Thanks, won't be able to check till Monday

**Comment by Tannenwedel** [comment]
Hi,

it now does find Microsoft.SqlServer.SqlEnum.dll. 

However, now these files are missing:

Microsoft.SqlServer.SqlClrProvider.dll
Microsoft.SqlServer.BatchParser.dll

both (Version=14.100.0.0)

**Comment by Seddryck** [comment]
It was my fear when I published this new version. I took less risk in the next attempt and included all the ```Microsoft.SqlServer.*.dll``` … hope it will fix it.

https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.45.build.436/artifacts

**Comment by Tannenwedel** [comment]
Thanks!

Still fails to pick up Microsoft.SqlServer.BatchParser.dll despite the file being present in the Framework directory.

Exception during the setup of the test: Could not load file or assembly 'Microsoft.SqlServer.BatchParser, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies.

**Comment by Seddryck** [comment]
In cas eyou need them, I just setup a file with all the SMO librairies that you could potentially need.
[Microsoft.SqlServer.Smo.zip](https://github.com/Seddryck/NBi/files/2243193/Microsoft.SqlServer.Smo.zip)


If the dlls are in the same folder than the application, have the exact same version and you can't use them, it's really really weird.

**Comment by Seddryck** [comment]
No news and I can't reproduce it.

**Comment by phampdx** [comment]
Hi, 
I was able to reproduce above issue with following your instructions but still get following error:
`
Errors and Failures:
1) Test Failure : NBi.NUnit.Runtime.TestSuite.TestId: 8124. Validate ETL of data
   Exception during the setup of the test: Could not load file or assembly 'Microsoft.SqlServer.BatchParser, Version=14.100.0.0, Culture=neu
tral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandl
eOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.SqlServer.Management.Common.ServerConnection.GetStatements(String query, ExecutionTypes executionType, Int32& statementsToRe
verse)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)

   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand)
   at NBi.Core.SqlServer.Smo.BatchRunCommand.Execute() in C:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core.SqlServe
r\Smo\BatchRunCommand.cs:line 35
   at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit
.Runtime\TestSuite.cs:line 169
at NBi.NUnit.Runtime.TestSuite.HandleExceptionDuringSetup(Exception ex) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\
NBi.NUnit.Runtime\TestSuite.cs:line 195
at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit.Ru
ntime\TestSuite.cs:line 180
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit.
Runtime\TestSuite.cs:line 115`

My .sql file very simple:

![image](https://user-images.githubusercontent.com/6032636/56764705-370fa300-675a-11e9-8d1e-5fe5fd36d509.png)

`  <test name="TestId: 8124. Validate data" uid="8124">
    <setup>
	  <sql-run connectionString="@mydb" name="my.sql" path="..\DimDataScenario\DM\" />		
    </setup>
    <system-under-test>
      <execution>
        <query> <![CDATA[  
		SELECT count(1)
		FROM dbo.DimData
		WHERE Deleted IS NULL
			AND DataKey > 0 
		]]>	</query>
      </execution>
    </system-under-test>
    <assert>`

Run with NBi version v1.19.

Thanks,


Khanh
